### ISSUE TITLE
perhaps an extra u in pid_t

### ISSUE THREAD

**Issue by GeraldCNelson** [r-spatial/sf#1325]
Whether I attempt to compile on my mac book pro (Catalina 10.15.4) from CRAN or GitHub, I get the same set of errors. They all look like a variant of the following

```
int      setsgroups_np(int, const uuid_t);
                                  ^
/usr/local/include/sys/_types/_uid_t.h:31:31: note: 'uid_t' declared here
```

The complete set of error message is 

> In file included from gdal_write.cpp:5:
> In file included from /usr/local/Cellar/gdal/2.4.4_2/include/ogrsf_frmts.h:35:
> In file included from /usr/local/Cellar/gdal/2.4.4_2/include/ogr_feature.h:35:
> In file included from /usr/local/Cellar/gdal/2.4.4_2/include/ogr_featurestyle.h:33:
> In file included from /usr/local/Cellar/gdal/2.4.4_2/include/cpl_conv.h:36:
> In file included from /usr/local/Cellar/gdal/2.4.4_2/include/cpl_vsi.h:62:
> In file included from /usr/local/include/unistd.h:655:
> /usr/local/include/gethostuuid.h:39:17: error: C++ requires a type specifier for all declarations
> int gethostuuid(uuid_t, const struct timespec *) __OSX_AVAILABLE_STARTING(__MAC_10_5, __IPHONE_NA);
>                 ^
> In file included from gdal_write.cpp:5:
> In file included from /usr/local/Cellar/gdal/2.4.4_2/include/ogrsf_frmts.h:35:
> In file included from /usr/local/Cellar/gdal/2.4.4_2/include/ogr_feature.h:35:
> In file included from /usr/local/Cellar/gdal/2.4.4_2/include/ogr_featurestyle.h:33:
> In file included from /usr/local/Cellar/gdal/2.4.4_2/include/cpl_conv.h:36:
> In file included from /usr/local/Cellar/gdal/2.4.4_2/include/cpl_vsi.h:62:
> /usr/local/include/unistd.h:662:27: error: unknown type name 'uuid_t'; did you mean 'uid_t'?
> int      getsgroups_np(int *, uuid_t);
>                               ^
> /usr/local/include/sys/_types/_uid_t.h:31:31: note: 'uid_t' declared here
> typedef __darwin_uid_t        uid_t;
>                               ^
> In file included from gdal_write.cpp:5:
> In file included from /usr/local/Cellar/gdal/2.4.4_2/include/ogrsf_frmts.h:35:
> In file included from /usr/local/Cellar/gdal/2.4.4_2/include/ogr_feature.h:35:
> In file included from /usr/local/Cellar/gdal/2.4.4_2/include/ogr_featurestyle.h:33:
> In file included from /usr/local/Cellar/gdal/2.4.4_2/include/cpl_conv.h:36:
> In file included from /usr/local/Cellar/gdal/2.4.4_2/include/cpl_vsi.h:62:
> /usr/local/include/unistd.h:664:27: error: unknown type name 'uuid_t'; did you mean 'uid_t'?
> int      getwgroups_np(int *, uuid_t);
>                               ^
> /usr/local/include/sys/_types/_uid_t.h:31:31: note: 'uid_t' declared here
> typedef __darwin_uid_t        uid_t;
>                               ^
> In file included from gdal_write.cpp:5:
> In file included from /usr/local/Cellar/gdal/2.4.4_2/include/ogrsf_frmts.h:35:
> In file included from /usr/local/Cellar/gdal/2.4.4_2/include/ogr_feature.h:35:
> In file included from /usr/local/Cellar/gdal/2.4.4_2/include/ogr_featurestyle.h:33:
> In file included from /usr/local/Cellar/gdal/2.4.4_2/include/cpl_conv.h:36:
> In file included from /usr/local/Cellar/gdal/2.4.4_2/include/cpl_vsi.h:62:
> /usr/local/include/unistd.h:727:31: error: unknown type name 'uuid_t'; did you mean 'uid_t'?
> int      setsgroups_np(int, const uuid_t);
>                                   ^
> /usr/local/include/sys/_types/_uid_t.h:31:31: note: 'uid_t' declared here
> typedef __darwin_uid_t        uid_t;
>                               ^
> In file included from gdal_write.cpp:5:
> In file included from /usr/local/Cellar/gdal/2.4.4_2/include/ogrsf_frmts.h:35:
> In file included from /usr/local/Cellar/gdal/2.4.4_2/include/ogr_feature.h:35:
> In file included from /usr/local/Cellar/gdal/2.4.4_2/include/ogr_featurestyle.h:33:
> In file included from /usr/local/Cellar/gdal/2.4.4_2/include/cpl_conv.h:36:
> In file included from /usr/local/Cellar/gdal/2.4.4_2/include/cpl_vsi.h:62:
> /usr/local/include/unistd.h:729:31: error: unknown type name 'uuid_t'; did you mean 'uid_t'?
> int      setwgroups_np(int, const uuid_t);
>                                   ^
> /usr/local/include/sys/_types/_uid_t.h:31:31: note: 'uid_t' declared here
> typedef __darwin_uid_t        uid_t;
>                               ^
> 5 errors generated.
> make: *** [gdal_write.o] Error 1
> ERROR: compilation failed for package ‘sf’
> * removing ‘/Users/gcn/Library/R/3.6/library/sf’
> * restoring previous ‘/Users/gcn/Library/R/3.6/library/sf’
> Error: Failed to install 'sf' from GitHub:
>   (converted from warning) installation of package ‘/var/folders/bv/881_rsvd2kv83c13yywwc_xh0000gp/T//RtmpYFJCKI/file478211fb688/sf_0.9-1.tar.gz’ had non-zero exit status

**Comment by edzer** [comment]
Have you looked at #1320 and #1317?

**Comment by GeraldCNelson** [comment]
We OSX mac users have been taught to expect that "it just works", especially with something on CRAN. :-) 

I followed the instructions from 1320 and still got errors. Then I did a couple of experiments. 

This code fails
`install.packages("sf", lib="/Library/Frameworks/R.framework/Versions/3.6/Resources/library")`

This code compiles successfully
`install.packages("sf")`

Not sure why the lib options fails.
