### ISSUE TITLE
Problem installing classInt (required for sf)

### ISSUE THREAD

**Issue by LeandroZipitria** [r-spatial/sf#2487]
Hi. I´m trying to install the package "classInt" required for package "SF" to work. I have a MAC Book, MAC OS Sequoia 15.1.1.

Also, have installed the C compiler and Fortran (see below).

The code is as follow:

> install.packages("classInt")
Installing package into ‘/usr/local/lib/R/4.4/site-library’
(as ‘lib’ is unspecified)
trying URL 'https://cran.rstudio.com/src/contrib/classInt_0.4-10.tar.gz'
Content type 'application/x-gzip' length 440271 bytes (429 KB)
==================================================
downloaded 429 KB

* installing *source* package ‘classInt’ ...
** package ‘classInt’ successfully unpacked and MD5 sums checked
** using staged installation
** libs
using C compiler: ‘Apple clang version 16.0.0 (clang-1600.0.26.4)’
using Fortran compiler: ‘GNU Fortran (Homebrew GCC 14.2.0_1) 14.2.0’
using SDK: ‘MacOSX15.1.sdk’
/usr/local/opt/gcc/bin/gfortran  -fPIC  -g -O2  -c fish1.f -o fish1.o
clang -I"/usr/local/Cellar/r/4.4.2_2/lib/R/include" -DNDEBUG   -I/usr/local/opt/gettext/include -I/usr/local/opt/readline/include -I/usr/local/opt/xz/include -I/usr/local/include    -fPIC  -g -O2  -c init.c -o init.o
clang -dynamiclib -Wl,-headerpad_max_install_names -undefined dynamic_lookup -L/usr/local/Cellar/r/4.4.2_2/lib/R/lib -L/usr/local/opt/gettext/lib -L/usr/local/opt/readline/lib -L/usr/local/opt/xz/lib -L/usr/local/lib -o classInt.so fish1.o init.o -L/usr/local/opt/gcc/lib/gcc/current/gcc/x86_64-apple-darwin23/14 -L/usr/local/opt/gcc/lib/gcc/current/gcc -L/usr/local/opt/gcc/lib/gcc/current -lemutls_w -lheapt_w -lgfortran -lquadmath -L/usr/local/Cellar/r/4.4.2_2/lib/R/lib -lR -lintl -Wl,-framework -Wl,CoreFoundation
ld: warning: search path '/usr/local/opt/gcc/lib/gcc/current/gcc/x86_64-apple-darwin23/14' not found
ld: library 'emutls_w' not found
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [classInt.so] Error 1
ERROR: compilation failed for package ‘classInt’
* removing ‘/usr/local/lib/R/4.4/site-library/classInt’
Warning in install.packages :
  installation of package ‘classInt’ had non-zero exit status

As far as I know, the gcc compiler is in the directory:

/usr/local/Cellar/gcc/14.2.0_1

It seems a problem of the directory where is pointing, but cannot figure out how to fix it. 

Any help appreciated.

Best,
Leandro

**Comment by edzer** [comment]
Have you tried
```r
install.packages("classInt", type = "binary")
```
?

**Comment by rsbivand** [comment]
Indeed, not an `sf` issue, the correct place to report would be https://github.com/r-spatial/classInt/issues, had the problem most likely not been caused by the use of the wrong Fortran compiler, which should be as specified in https://mac.r-project.org/tools/. I'll check that source installation works on macOS 15.1.1 with the specified compiler (not homebrew) on arm64 and report back.

**Comment by rsbivand** [comment]
With:
```
% gfortran --version
GNU Fortran (GCC) 12.2.0
Copyright (C) 2022 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

 % clang --version
Apple clang version 14.0.0 (clang-1400.0.29.202)
Target: arm64-apple-darwin24.1.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
```
and 0.4-10, installation is fine:
```
* installing *source* package ‘classInt’ ...
** package ‘classInt’ successfully unpacked and MD5 sums checked
** using staged installation
** libs
using C compiler: ‘Apple clang version 14.0.0 (clang-1400.0.29.202)’
using Fortran compiler: ‘GNU Fortran (GCC) 12.2.0’
using SDK: ‘MacOSX15.1.sdk’
/opt/gfortran/bin/gfortran -arch arm64  -fPIC  -Wall -g -O2  -c fish1.f -o fish1.o
clang -arch arm64 -I"/Library/Frameworks/R.framework/Resources/include" -DNDEBUG   -I/opt/R/arm64/include    -fPIC  -falign-functions=64 -Wall -g -O2  -c init.c -o init.o
clang -arch arm64 -dynamiclib -Wl,-headerpad_max_install_names -undefined dynamic_lookup -L/Library/Frameworks/R.framework/Resources/lib -L/opt/R/arm64/lib -o classInt.so fish1.o init.o -L/opt/gfortran/lib/gcc/aarch64-apple-darwin20.0/12.2.0 -L/opt/gfortran/lib -lgfortran -lemutls_w -lquadmath -F/Library/Frameworks/R.framework/.. -framework R -Wl,-framework -Wl,CoreFoundation
ld: warning: -undefined dynamic_lookup may not work with chained fixups
ld: warning: could not create compact unwind for _fish_: registers 21 and 22 not saved contiguously in frame
ld: warning: could not create compact unwind for ___emutls_get_address: registers 23 and 24 not saved contiguously in frame
installing to /Users/rogerbivand/Documents/topics/packages/github-r-spatial/classInt.Rcheck/00LOCK-classInt/00new/classInt/libs
** R
** inst
** byte-compile and prepare package for lazy loading
** help
*** installing help indices
** building package indices
** installing vignettes
** testing if installed package can be loaded from temporary location
** checking absolute paths in shared objects and dynamic libraries
** testing if installed package can be loaded from final location
** testing if installed package keeps a record of temporary installation path
* DONE (classInt)
```
with check log: 
[00check.log](https://github.com/user-attachments/files/18059319/00check.log)

The problem is caused by the use of the wrong build train, the instructions in https://mac.r-project.org/tools/ should be followed exactly.

**Comment by LeandroZipitria** [comment]
Thanks for the answers. @rsbivand, as far as I understand, the problem is that Fortran is installed from Brew. I have also downloaded from https://mac.r-project.org/tools/, so I have two installations. How should I uninstall the Brew installation of Fortran? I tried it "raw" and have been advised that many programs (such as Julia, R, etc.) should also be uninstalled.

Thanks,
Leandro

**Comment by rsbivand** [comment]
@LeandroZipitria Please explain why you want to install these packages from source. We know nothing about homebrew, it is never used to build R itself for releases. Do use binary packages unless you have to install from source, and understand that on macOS or Windowsm no support is available if not using the standard R installation build trains.

**Comment by LeandroZipitria** [comment]
> ```r
> install.packages("classInt", type = "binary")
> ```

@edzer, please see below:

> install.packages("classInt", type = "binary")
Error in install.packages : type 'binary' is not supported on this platform

**Comment by LeandroZipitria** [comment]
> @LeandroZipitria Please explain why you want to install these packages from source. We know nothing about homebrew, it is never used to build R itself for releases. Do use binary packages unless you have to install from source, and understand that on macOS or Windowsm no support is available if not using the standard R installation build trains.

First, let me copy the data for R:

R version 4.4.2 (2024-10-31) -- "Pile of Leaves"
Copyright (C) 2024 The R Foundation for Statistical Computing
Platform: x86_64-apple-darwin23.6.0

I download all package and install them locally. See below:

> install.packages("~/Downloads/classInt_0.4-10.tgz", repos = NULL, type = .Platform$pkgType)
Installing package into ‘/usr/local/lib/R/4.4/site-library’
(as ‘lib’ is unspecified)
* installing *binary* package ‘classInt’ ...
* DONE (classInt)
> install.packages("~/Downloads/sf_1.0-15.tgz", repos = NULL, type = .Platform$pkgType)
Installing package into ‘/usr/local/lib/R/4.4/site-library’
(as ‘lib’ is unspecified)
* installing *binary* package ‘sf’ ...
* DONE (SF)

Then, I tried to load them, and have the following result:

> library(sf)
Error: package or namespace load failed for ‘sf’ in dyn.load(file, DLLpath = DLLpath, ...):
 unable to load shared object '/usr/local/lib/R/4.4/site-library/classInt/libs/classInt.so':
  dlopen(/usr/local/lib/R/4.4/site-library/classInt/libs/classInt.so, 0x0006): Library not loaded: /Library/Frameworks/R.framework/Versions/4.2/Resources/lib/libgfortran.5.dylib
  Referenced from: <4AA8CFA3-0705-3EE3-9E6C-9F9DE2E0FF36> /usr/local/lib/R/4.4/site-library/classInt/libs/classInt.so
  Reason: tried: '/Library/Frameworks/R.framework/Versions/4.2/Resources/lib/libgfortran.5.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/Library/Frameworks/R.framework/Versions/4.2/Resources/lib/libgfortran.5.dylib' (no such file), '/Library/Frameworks/R.framework/Versions/4.2/Resources/lib/libgfortran.5.dylib' (no such file), '/usr/local/Cellar/r/4.4.2_2/lib/R/lib/libgfortran.5.dylib' (no such file), '/var/folders/3b/8h0jn3612h92nglh6d_2qnxw0000gn/T/rstudio-fallback-library-path-215886601/libgf

This is the original problem I get if I try to download and compile the package "sf". When done it, it says that it need to also download "classInt" and the error arise. My original post is for when I tried to install "sf" it also install "classInt" and exit. So I just post the "classInt" installation.

Thanks
Leandro

**Comment by rsbivand** [comment]
What is your platform? I guess a homebrew R binary, which of course does not support binary installs. Nobody can help you if you did not install the CRAN R binary, which uses the same build train as binary builds of contributed packages.

**Comment by rsbivand** [comment]
No idea. You should.not install R using homebrew. I never use homebrew. Use Xcode and the gfortran from CRAN,  if you have to install source packages.

**Comment by LeandroZipitria** [comment]
Dear @edzer and @rsbivand. I have uninstall R from homebrew, install it from CRAN R, reinstall all packages, and now it works fine! No need to compile anything, and everything working ok.

My apologizes for all the inconvenience.

**Comment by rsbivand** [comment]
@LeandroZipitria As an explanation, it is not impossible to treat macOS as Unix, and install all the build train and external software components from source, or at least those components not provided by the platform. But homebrew is built on top of the platform, so mixing Apple clang and llvm build train choices with choices made by external software adds an extra level of assumptions. 

CRAN and R chose for Windows and macOS from the beginning (> 20 years ago) to provide R binaries and binaries of contributed packages to disambiguate the assumptions made in installation of R and of contributed packages. For Windows and macOS, binary contributed packages are built statically linked, so that all of the external software components used by the compiled code in the contributed package are known to have been built using the same set of assumptions (the same build train) as R itself. 

Why? Because when build trains are mixed, odd and hard to diagnose errors can appear, for example in accessing unassigned memory, which then yield odd results. On Unix/Linux, we know that for a given release of Fedora or Ubuntu, all the system-provided external software libraries have been built with the same compiler major version, so building R, PROJ, GDAL, GEOS etc. from source, then installing `sf` from source uses the same build train (compilers, linkers, loaders), and contributed packages can be built using dynamic linking.

**Comment by LeandroZipitria** [comment]
Dear @rsbivand, thanks for taking the time to explain how R works. To be honest, I do not usually look at how programs work, and it usually works. This time it doesn't, and I got a great free lesson. I appreciate the time you dedicated to helping me with this issue, which I know is valuable and scarce time.  

Thanks again,
Leandro
